### PR TITLE
Update FathomAnalytics.php

### PR DESCRIPTION
**Pull request by austinginder**
Fix for Fathom v3 launch to resolve issues #3

### CODE REVIEW

**Review by tectonic-pg — COMMENTED** [review]
I think the submit button for 2FA needs to be updated as well

```php
$this->browser->submitForm('Login', [
    'one_time_password' => $oneTimePassword,
]);
```

**Comment by austinginder** [comment]
Updated

**Comment by ndeblauw** [comment]
I confirm, this fix resolves the issue. Nice work @austinginder

**Comment by ndeblauw** [comment]
@mpociot @sschlein Could you please merge this (small, innocent & bug fixing) PR into the master branch and release it? Shouldn't take more than 5 minutes, and it really helps us forward!

**Pull request merged**
